import { Instruction } from '@prisma/client'

export const mockInstructions: Instruction[] = [
  {
    id: 'testinstruction1',
    recipeId: 'testrecipe0',
    step: 1,
    title: '',
    photo: 'testrecipe0/thumbnail-jpg',
    methods: [
      'Pour the stock into a pan and add the chicken breast, ginger and garlic.',
      'Bring to the boil, then reduce the heat, partly cover and simmer for 20 mins, until the chicken is tender.',
    ],
  },
  {
    id: 'testinstruction2',
    recipeId: 'testrecipe0',
    step: 2,
    title: '',
    photo: 'testrecipe0/thumbnail-jpg',
    methods: [
      'Put the chicken on a board and shred into bite-size pieces using a couple of forks. Return the chicken to the stock with the noodles, sweetcorn, mushrooms, spring onion and soy sauce.',
      'Simmer for 3-4 mins until the noodles are tender.',
    ],
  },
  {
    id: 'testinstruction3',
    recipeId: 'testrecipe0',
    step: 3,
    title: 'testStep1',
    photo: 'testrecipe0/thumbnail-jpg',
    methods: [
      'Ladle into two bowls and scatter over the remaining spring onion, mint or basil leaves and chilli, if using.',
      'Serve with extra soy sauce.s',
    ],
  },

  {
    id: 'testinstruction4',
    recipeId: 'testrecipe1',
    step: 1,
    title: '',
    photo: 'testrecipe1/thumbnail-jpg',
    methods: ['Preheat a grill pan over medium-high heat.'],
  },
  {
    id: 'testinstruction5',
    recipeId: 'testrecipe1',
    step: 2,
    title: '',
    photo: 'testrecipe1/thumbnail-jpg',
    methods: [
      'Sprinkle the shrimp in a bowl with the oregano, 1 tablespoon olive oil, 1/2 teaspoon salt and a pinch of pepper.',
    ],
  },
  {
    id: 'testinstruction6',
    recipeId: 'testrecipe1',
    step: 3,
    title: '',
    photo: 'testrecipe1/thumbnail-jpg',
    methods: [
      'Heat a skillet over medium-high heat, then add the butter and let melt.',
      'Add the flour and cook, 1 minute.',
      'Add the garlic and continue to cook, whisking, 1 minute more.',
      'Whisk in the milk and cook until very thick, 2 to 3 minutes.',
      'Stir in 1/4 cup Parmesan and remove from the heat.',
      'Season with a pinch of salt and pepper.',
    ],
  },
  {
    id: 'testinstruction7',
    recipeId: 'testrecipe1',
    step: 4,
    title: '',
    photo: 'testrecipe1/thumbnail-jpg',
    methods: ['Preheat the broiler to high.'],
  },
  {
    id: 'testinstruction8',
    recipeId: 'testrecipe1',
    step: 5,
    title: '',
    photo: 'testrecipe1/thumbnail-jpg',
    methods: [
      'Roll out the pizza dough on a lightly-floured work surface into two 10-inch ovals. s',
      'Brush the grill pan with the remaining tablespoon olive oil.',
      'Grill the dough on both sides until there are grill marks, 2 to 3 minutes per side.',
      'Remove the crusts to a sheet tray.',
      'Add the shrimp to the grill pan and grill on both sides until fully cooked, pink and opaque, about 4 minutes total.',
      'Spread the white sauce on the dough in an even layer.',
      'Scatter the shrimp over the sauce.',
      'Sprinkle with the mozzarella and the remaining 1/4 cup Parmesan.',
      "Place under the broiler until the cheese is melted and bubbly, keeping a close eye so it doesn't burn, 2 to 7 minutes. ",
      'Sprinkle the red pepper flakes and parsley on top before serving.',
    ],
  },
  {
    id: 'testinstruction9',
    recipeId: 'testrecipe2',
    step: 1,
    title: 'testStep1',
    photo: 'testrecipe2/thumbnail-jpg',
    methods: [
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
    ],
  },
]
