import { Instruction } from '@prisma/client'

export const mockInstructions: Instruction[] = [
  {
    id: 'testinstruction1',
    recipeId: 'testrecipe0',
    step: 1,
    title: 'testStep1',
    photo: 'testrecipe0/thumbnail-jpg',
    methods: [
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
    ],
  },
  {
    id: 'testinstruction2',
    recipeId: 'testrecipe0',
    step: 2,
    title: 'testStep1',
    photo: 'testrecipe0/thumbnail-jpg',
    methods: [
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
    ],
  },
  {
    id: 'testinstruction3',
    recipeId: 'testrecipe0',
    step: 3,
    title: 'testStep1',
    photo: 'testrecipe0/thumbnail-jpg',
    methods: [
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
    ],
  },
  {
    id: 'testinstruction4',
    recipeId: 'testrecipe0',
    step: 4,
    title: 'testStep1',
    photo: 'testrecipe0/thumbnail-jpg',
    methods: [
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
    ],
  },
  {
    id: 'testinstruction5',
    recipeId: 'testrecipe0',
    step: 5,
    title: 'testStep1',
    photo: 'testrecipe0/thumbnail-jpg',
    methods: [
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
    ],
  },
  {
    id: 'testinstruction6',
    recipeId: 'testrecipe1',
    step: 1,
    title: 'testStep1',
    photo: 'testrecipe1/thumbnail-jpg',
    methods: [
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
    ],
  },
  {
    id: 'testinstruction7',
    recipeId: 'testrecipe1',
    step: 2,
    title: 'testStep1',
    photo: 'testrecipe1/thumbnail-jpg',
    methods: [
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
    ],
  },
  {
    id: 'testinstruction8',
    recipeId: 'testrecipe1',
    step: 3,
    title: 'testStep1',
    photo: 'testrecipe1/thumbnail-jpg',
    methods: [
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
    ],
  },
  {
    id: 'testinstruction9',
    recipeId: 'testrecipe2',
    step: 1,
    title: 'testStep1',
    photo: 'testrecipe2/thumbnail-jpg',
    methods: [
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
      'Preheated 400 degrees F (200 degrees C) oven for 5 to 8 minutes',
    ],
  },
]
